### PR TITLE
Add Tekton resources

### PR DESCRIPTION
**Pull request by anatoliyfedorenko**
@tzununbekov have a look. I have no idea why build for Client package fails on CI

### CODE REVIEW

**Comment by anatoliyfedorenko** [comment]
Also, what about the size? Seems like it is now less than 50mb of additional data? This all comes from vendor :( maybe I have poor dep setup?

**Comment by tzununbekov** [comment]
I don't know how you do this, but if I run `dep ensure` in this branch, it removes all extra 150Mb of new dependencies. Again, we can't merge this into master.

**Comment by anatoliyfedorenko** [comment]
> I don't know how you do this, but if I run `dep ensure` in this branch, it removes all extra 150Mb of new dependencies. Again, we can't merge this into master.

I do not know as well... just `dep ensure` makes it :( anyway, I cleaned up. @tzununbekov still cannot reporoduce errors locally.

**Comment by tzununbekov** [comment]
It's still too much - your changes requires 571 lines of dependency code, you're trying to push 256517

**Comment by anatoliyfedorenko** [comment]
@tzununbekov what about now? Updated `dep` to newest version, seems like i had very old `dep`

**Pull request closed without merging**
