### PR TITLE
#102 Add Tekton resources

### PR DESCRIPTION
**Pull request by anatoliyfedorenko**
@tzununbekov @sebgoa this add only necessary dependencies. Please, review

### CODE REVIEW

**Comment by tzununbekov** [comment]
1. Why wouldn't we name tekton's `pipelineresource` as `pipeline` to match the format of all other resources and for better usability?  
2. Tests for new resources?

**Comment by anatoliyfedorenko** [comment]
> 1. Why wouldn't we name tekton's `pipelineresource` as `pipeline` to match the format of all other resources and for better usability?
> 2. Tests for new resources?

@tzununbekov Because Pipeline and PipelineResources are two different things as I understood from documentation and @sebgoa requested CRUD for PipelineResources not Pipeline. 

Tests are not added yet. Will work on them today.

**Comment by anatoliyfedorenko** [comment]
But will double check everything. If it is not true, will adjust naming

**Comment by tzununbekov** [comment]
ok, thanks. Waiting for tests and then merge

**Comment by sebgoa** [comment]
correct, `pipelineresources` are inputs to `pipelines` . two different API objects

**Comment by anatoliyfedorenko** [comment]
@tzununbekov I added tests. they pass, but now the CI fails at validation stage. What could go wrong? `./script/validate-lint: line 12: golint: command not found`

**Pull request closed without merging**
