### PR TITLE
#9 Test build resource. Change filename for package entry

### PR DESCRIPTION
**Pull request by anatoliyfedorenko**
@tzununbekov Implemented tests for `build` package. One thing to note here is that I have chaged filename from `types.go` to `build.go` for the reason of readability. I guess go packages always have their "entrypoints" files which correspond to their names. So, that it why it would be more intuitive instead of having 'types.go' file in each package, to have a file named after a package. 

If that is not OK, I can change it back. The overall functionality does not change after all.

### CODE REVIEW

**Comment by tzununbekov** [comment]
I don't agree that renaming `types.go` improves readability. Each resource package has go files named as verbs (eg. `build` resource has `delete` action which defined in `build/delete.go`) and `types.go` which contains resource type itself. Having structures described in files named as verbs (`build/build.go`) is confusing. 

> go packages always have their "entrypoints" files which correspond to their names 

Where did you get it from? I know lots of projects which stores its structures in dedicated `types.go`, but I can use better practice if you provide one

**Comment by anatoliyfedorenko** [comment]
@tzununbekov you are right. Will rename it back. Did not find any evidence that support my point.

**Comment by anatoliyfedorenko** [comment]
@tzununbekov please, check it out . If tests are OK. I will do the same way for every other package.

**Comment by tzununbekov** [comment]
It's ok for now, but it would be great to have `defer`-ed handlers to cleanup test objects in case of test failure. For example, take a look at knative's e2e tests - https://github.com/knative/build/blob/master/test/e2e/simple_test.go especially [this](https://github.com/knative/build/blob/master/test/e2e/simple_test.go#L54-L56) part

**Pull request merged**
